### **1. What Linear Regression training algorithm can you use if you have a training set with millions of features?**
##### Gradient Descent: Vẫn đề là nếu có local minnimum thì khó thoát ra được. Nhưng vì hàm MSE(theta) là hàm lồi (Chọn bất kì 1 đoạn thẳng chúng sẽ không bao giờ cắt qua đường cong ==> không ccó local minimum. GD tốt cho mô hình hồi quy quyến tính
(The problem is that if there is local minnimum, it is difficult to exit. But since MSE(theta) function is convex function (Choose any line segment they will never cross the curve ==> there is no local minimum GD is good for charming regression model)
+ 1.1 Batch gradient descent: global minimum +- epsilon.Tùy thuộc vào épilon mà thuật toán nhanh hay chậm (Depending on epsilon and the algorithm is fast or slow)
    >+ GD . batch problem: sử dụng toàn bộ tập huấn luyện để tính toán gradient at every steps (use the entire training set to compute the gradient at every steps) => slow if training set is large
+ 1.2 stochastic gradient descent: 
    >+ Chỉ chọn một phiên bản ngẫu nhiêu trong tập huấn luyện ở mỗi bước và tính toán ggiá trị gradient dựa trên một phiên bản duy nhất đó. => Thuật toán trở nên nhanh hơn vì có ít thao tác với dữ liệu hơn ở mỗi lần lặp. (Pick only one random version of the training set at each step and compute the gradient value based on that single instance. => The algorithm becomes faster because there are fewer data manipulations at each iteration.)
    >+ Kết quả thu được chỉ ở mức tối thiểu không bằng Batch gradient descent nhưng lại có thể tránh được local minimum nếu có.(The results obtained are only at a minimum not equal to Batch gradient descent, but the local minimum can be avoided if at all.)
+ 1.3 Mini-batch gradient descent: 
    >+ Thay vì tính toán gradient descent trên tập huấn luyện đầy đủ (GD), hoặc trên 1 phiên bản (SGD), Mini_Batch GD tính toán gradient descent trên các tập hợp ngẫu nhiên gọi là các Mini_Batch (Instead of computing gradient descent on the full training set (GD), or on one instance (SGD), Mini_Batch GD computes gradient descent over random sets called Mini_Batchs.)
    >+ Result is better SGD but but it's hard to pass the local minimum (nhưng khó vượt qua được local minimum).

>+ **SGD và MBGD sẽ hoạt động tốt nhất vì cả hai đều không cần tải toàn bộ tập dữ liệu vào bộ nhớ để thực hiện 1 bước giảm độ dốc. Hàng loạt sẽ ổn với cảnh báo rằng bạn có đủ bộ nhớ để tải tất cả dữ liệu.**

### **2. Suppose the features in your training set have very different scales: what algorithms might suffer from this, and how? What can you do about it?**
+ Khi làm việc với tập dữ liệu. Chúng ta phải đối diện với vấn đề là giá trị giữa các đặc trưng ( feature) cách nhau quá xa. Điều này khiến cho việc chạy vòng lặp Gradient descent trở nên khó khăn hơn. Vì thế có một thủ thuật gọi là feature scaling giúp cho giá trị các feature gần nhau hơn và điều này khiến cho việc chạy Gradient descent được nhanh hơn
+ Phương pháp **Normal Equation** không yêu cầu chuẩn hóa các tính năng, vì vậy nó vẫn không bị ảnh hưởng bởi các tính năng trong tập huấn luyện có tỷ lệ rất khác nhau.


### **3. Can Gradient Descent get stuck in a local minimum when training a Logistic Regression model?**
>+ Ở hồi quy tuyến tính mô hình Gradient Descent là một hàm lồi. Cho nên không gặp vấn đề với các local minimum ( vì không có local minimum mà chỉ có duy nhât global minimum ở đáy thôi) - In linear regression, the Gradient Descent model is a convex function. So there's no problem with local minimums (because there's no local minimum, only a global minimum at the bottom).

### **4. Do all Gradient Descent algorithms lead to the same model provided you let them run long enough?**
>+ No. The issue is that stochastic gradient descent and mini-batch gradient descent have randomness built into them. This means that they can find their way to nearby the global optimum, but they generally don't converge. One way to help them converge is to gradually reduce the learning rate hyperparameter.

### **5. Suppose you use Batch Gradient Descent and you plot the validation error at every epoch. If you notice that the validation error consistently goes up, what is likely going on? How can you fix this?**
>+ Nếu lỗi xác thực liên tục tăng lên sau mỗi kỷ nguyên, thì một khả năng là tỷ lệ học tập quá cao và thuật toán đang phân kỳ. Nếu lỗi đào tạo cũng tăng lên, thì đây rõ ràng là vấn đề và bạn nên giảm tỷ lệ học.
>+ Tuy nhiên, nếu lỗi đào tạo không tăng lên, thì mô hình của bạn dang bi overfitting và bạn nên ngừng đào tạo và áp dụng các biện pháp khắc phục phổ biến cho việc ovefiting

### 6. Is it a good idea to stop Mini-batch Gradient Descent immediately when the validation error goes up?
+ Both Mini-batch and Stochastic gradient descent are not guarenteed to minimize the cost function after each step because the both have a degree of randomness built into them
+ Mini-bath randomly chooses which training examples to perform gradient descent on while Stochastic randomly chooses a single example.
+ A better option is to save the model at regular intervals. When the model has not improved for a long time you can revert to the saved models.
>+ Cả hai bước giảm dần theo lô nhỏ và giảm độ dốc Stochastic đều không được đảm bảo để giảm thiểu hàm chi phí sau mỗi bước vì cả hai đều có mức độ ngẫu nhiên được tích hợp sẵn. Mini-bath chọn ngẫu nhiên các ví dụ đào tạo để thực hiện giảm độ dốc trong khi Stochastic chọn ngẫu nhiên một ví dụ duy nhất. Một lựa chọn tốt hơn là lưu mô hình theo các khoảng thời gian đều đặn. Khi mô hình không được cải thiện trong một thời gian dài, bạn có thể hoàn nguyên về các mô hình đã lưu.

### **7. Which Gradient Descent algorithm (among those we discussed) will reach the vicinity of the optimal solution the fastest? Which will actually converge? How can you make the others converge as well?**
+ Stochastic gradient descent là nhanh nhất để hội tụ vì nó chỉ xem xét một ví dụ đào tạo tại một thời điểm.
+ Batch gradient descent được đảm bảo hội tụ với tốc độ học đủ nhỏ nhưng sẽ mất nhiều thời gian
+ Vì SGD và MBGD đều là ngẫu nhiên, một chiến lược bạn có thể sử dụng để giúp chúng hội tụ là giảm tốc độ học tập theo thời gian để nó thực hiện các bước giảm dần độ dốc ngày càng nhỏ khi nó đạt đến mức tối thiểu toàn cầu.

### **8. Giả sử bạn đang sử dụng Polynomial Regression. Bạn vẽ các đường cong học tập và bạn nhận thấy rằng có một khoảng cách lớn giữa lỗi đào tạo và lỗi xác nhận. Điều gì đang xảy ra? Ba cách để giải quyết vấn đề này là gì?**

>+ **Answer:** Khi bạn vẽ các đường cong học tập và nhận thấy có một khoảng cách lớn giữa lỗi đào tạo và lỗi xác thực, đó là đặc điểm của mô hình overfitting. "Khoảng trống" tồn tại đơn giản vì lỗi đào tạo thấp hơn lỗi xác nhận. Một cách để phát triển mô hình overfitting là cung cấp thêm dữ liệu đào tạo. Một chiến thuật khác là giảm độ phức tạp của mô hình. Bạn cũng có thể giảm số lượng tính năng trong dữ liệu của mình. Một điều cuối cùng cần thử là thêm chính quy hóa vào mô hình của bạn. L2 (Ridge Regression) hoặc L1 (Lasso) là những lựa chọn tốt.
>+ Nếu mô hình hoạt động tốt trên tập dữ liệu huấn luyện nhưng lại kém trên tập dữ liệu xác thực =>> Overfitting (If the model performs well on the training data set but poorly on the validation dataset =>> Overfitting)
>+ Nếu mô hình kém trên cả 2 => Underfitting
>+ If model is underfitting training data, adding more trainig examples will not help. You need to use a more complex model or come up eith better features.


### **9. Suppose you are using Ridge Regression and you notice that the training error and the validation error are almost equal and fairly high. Would you say that the model suffers from high bias or high variance? Should you increase the regularization hyperparameter α or reduce it?**
+ When the training error and validation error are close to each other and high that means your model is underfitting (i.e. it has high bias). You should try to reduce the regularization hyperparameter.

### **10. Why would you want to use: Ridge Regression instead of plain Linear Regression (i.e., without any regularization)? or Lasso instead of Ridge Regression or Elastic Net instead of Lasso?**
+ Ridge Regression tốt nhưng nếu dữ liệu chỉ có một số tính năng hiệu quả thì nên chọn Lasso hoặc Elastic vì chúng có xu hướng giảm trọng số của các tính năng vô dụng. (Ridge Regression is good but if the data has only some effective features then Lasso or Elastic should be chosen as they tend to reduce the weight of useless features.)
+ Ridge regression instead of Linear Regression?
Use Ridge regression when your model is overfitting the training set. If you think only several features in your training set are useful, go with lasso or elastic net.
+  Lasso thay vì hồi quy Ridge?
Lasso thực hiện lựa chọn tính năng tự động bằng cách giảm trọng lượng của các tính năng quan trọng nhất. Cụ thể, hồi quy Lasso sử dụng hình phạt l1 có xu hướng đẩy trọng số xuống chính xác bằng không. Điều này dẫn đến các mô hình thưa thớt, trong đó tất cả các trọng số đều bằng 0 ngoại trừ các trọng số quan trọng nhất. Đây là một cách để thực hiện tự động lựa chọn tính năng, điều này rất tốt nếu bạn nghi ngờ rằng chỉ có một số tính năng thực sự quan trọng. Khi bạn không chắc chắn, bạn nên thích hồi quy Ridge hơn.
+ Elastic Net thay vì Lasso? Elastic Net được ưu tiên hơn Lasso vì Lasso có thể hoạt động thất thường khi số lượng tính năng nhiều hơn số lượng trường hợp huấn luyện hoặc khi một số tính năng có tương quan chặt chẽ.



### **11. Suppose you want to classify pictures as outdoor/indoor and daytime/nighttime. Should you implement two Logistic Regression classifiers or one Softmax Regression classifier?**
+ Use softmax Regression Because this is a multi-class classification problem - Not a multi-output problem
+ Softmax regression does not handle multiple output classes (i.e. [indoor, daytime]). So you'll need to use two logistic regression classsifiers

## **12. Implement Batch Gradient Descent with early stopping for Softmax Regression (without using Scikit-Learn)**

In [43]:
from sklearn import datasets
import numpy as np

iris = datasets.load_iris()
list(iris.keys())

['data',
 'target',
 'frame',
 'target_names',
 'DESCR',
 'feature_names',
 'filename',
 'data_module']

In [44]:
iris["target"] # It is multinomial classification

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [45]:
iris["feature_names"]

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [46]:
X = iris["data"][:, (2, 3)]  # petal length, petal width
y = iris["target"]

In [47]:
X_with_bias = np.c_[np.ones([len(X), 1]), X]
X_with_bias[:3]

array([[1. , 1.4, 0.2],
       [1. , 1.4, 0.2],
       [1. , 1.3, 0.2]])

In [48]:
np.random.seed(2042)

In [49]:
# Train_test_split
test_ratio = 0.2
validation_ratio = 0.2
total_size = len(X_with_bias)

test_size = int(total_size * test_ratio)
validation_size = int(total_size * validation_ratio)
train_size = total_size - test_size - validation_size

rnd_indices = np.random.permutation(total_size)

X_train = X_with_bias[rnd_indices[:train_size]]
y_train = y[rnd_indices[:train_size]]
X_valid = X_with_bias[rnd_indices[train_size:-test_size]]
y_valid = y[rnd_indices[train_size:-test_size]]
X_test = X_with_bias[rnd_indices[-test_size:]]
y_test = y[rnd_indices[-test_size:]]


+ Các mục tiêu hiện là chỉ số lớp (0, 1 hoặc 2), nhưng chúng ta cần xác suất lớp mục tiêu để đào tạo mô hình Hồi quy Softmax.
+ Hãy viết một hàm nhỏ để chuyển đổi vectơ của các chỉ số lớp thành một ma trận chứa một vectơ một hot cho mỗi trường hợp
+ [1,0,1,2] - > [[0,1,0], [1,0,0], [0,1,0], [0,0,1]]

In [50]:
def to_one_hot(y):
    n_classes = y.max() + 1
    m = len(y)
    y_one_hot = np.zeros((m,n_classes)) # Tao mot ma tran co m x n_classes gia tri  = 0
    y_one_hot[np.arange(m), y] = 1
    return y_one_hot


In [51]:
y_train[:10]

array([0, 1, 2, 1, 1, 0, 1, 1, 1, 0])

In [52]:
to_one_hot(y_train[:10])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [54]:
Y_train_one_hot = to_one_hot(y_train)
Y_valid_one_hot = to_one_hot(y_valid)
Y_test_one_hot = to_one_hot(y_test)

Now let's implement the Softmax function. Recall that it is defined by the following equation:

$\sigma\left(\mathbf{s}(\mathbf{x})\right)_k = \dfrac{\exp\left(s_k(\mathbf{x})\right)}{\sum\limits_{j=1}^{K}{\exp\left(s_j(\mathbf{x})\right)}}$

In [56]:
def softmax(logits):
    exps = np.exp(logits)
    exp_sums = np.sum(exps, axis=1, keepdims=True)
    return exps/exp_sums

In [66]:
n_inputs = X_train.shape[1] # == 3 (2 features plus the bias term)
n_outputs = len(np.unique(y_train))

In [71]:
eta = 0.01
n_iterators = 10001
m = len(X_train)
epsilon = 1e-7

Theta = np.random.randn(n_inputs, n_outputs)

for iteration in range(n_iterators):
    logits = X_train.dot(Theta)
    Y_proba = softmax(logits)
    if iteration % 500 == 0:
        loss = -np.mean(np.sum(Y_train_one_hot * np.log(Y_proba + epsilon), axis=1))
        print(iteration, loss)
    error = Y_proba - Y_train_one_hot
    gradients = 1/m * X_train.T.dot(error)
    Theta = Theta - eta * gradients

0 3.207870888733737
500 0.9102655715933011
1000 0.7245981143541181
1500 0.6195736452392622
2000 0.5544764557510471
2500 0.5101215223249341
3000 0.4775255492382668
3500 0.4521715148580381
4000 0.4315976459646628
4500 0.41436168630147824
5000 0.3995652334938366
5500 0.38661917369282717
6000 0.37512021585913286
6500 0.3647820739246793
7000 0.35539515332865773
7500 0.3468018945680141
8000 0.3388811161978051
8500 0.3315377410307348
9000 0.3246958576155642
9500 0.31829391347903546
10000 0.3122813091198972


+ Make predictions for the validation set and check the accuracy score

In [72]:
Theta

array([[ 3.77808488, -0.93784458, -4.49782649],
       [-0.72657914,  0.61516885,  0.31615831],
       [-1.57146073, -0.12495489,  3.00451718]])

In [73]:
logits = X_valid.dot(Theta)
Y_proba = softmax(logits)
y_predict = np.argmax(Y_proba, axis=1)

accuracy_score = np.mean(y_predict == y_valid)
accuracy_score

0.9666666666666667

+ Try incresing eta - learning rate

In [75]:
eta = 0.05
n_iterations = 5001
m = len(X_train)
epsilon = 1e-7
alpha = 0.1  # regularization hyperparameter

Theta = np.random.randn(n_inputs, n_outputs)

for iteration in range(n_iterations):
    logits = X_train.dot(Theta)
    Y_proba = softmax(logits)
    if iteration % 500 == 0:
        xentropy_loss = -np.mean(np.sum(Y_train_one_hot * np.log(Y_proba + epsilon), axis=1))
        l2_loss = 1/2 * np.sum(np.square(Theta[1:]))
        loss = xentropy_loss + alpha * l2_loss
        print(iteration, loss)
    error = Y_proba - Y_train_one_hot
    gradients = 1/m * X_train.T.dot(error) + np.r_[np.zeros([1, n_outputs]), alpha * Theta[1:]]
    Theta = Theta - eta * gradients

0 3.499703253536928
500 0.5734682734831308
1000 0.529126622350338
1500 0.5116108165765126
2000 0.5025890477442458
2500 0.49742818248808907
3000 0.49431546689203937
3500 0.49237806618330915
4000 0.4911469378188872
4500 0.4903531442866595
5000 0.4898358572772569


In [76]:
logits = X_valid.dot(Theta)
Y_proba = softmax(logits)
y_predict = np.argmax(Y_proba, axis=1)

accuracy_score = np.mean(y_predict == y_valid)
accuracy_score

1.0

+ ADD EARLY STOPPING